version: '2'

services:
 postgres:
   image: postgres
   volumes:
     - db_data:/var/lib/postgres
   restart: always
   environment:
     POSTGRES_DB: otrs

 otrs:
   depends_on:
     - postgres
   image: uolcz/otrs-for-docker
   ports:
     - "80:80"
   restart: always

volumes:
  db_data:
